<?php

declare(strict_types=1);

/**
 * Implements \hook_page_attachments().
 *
 * Super basic Mastodon site verification.
 *
 * @see https://til.simonwillison.net/mastodon/verifying-github-on-mastodon
 */
function ambientimpact_verification_page_attachments(
  array &$attachments
): void {

  $attachments['#attached']['html_head_link'][] = [
    [
      'rel'   => 'me',
      'href'  => 'https://indieweb.social/@ambientimpact',
    ],
  ];

}
